#param([Parameter(Mandatory = $TRUE)][Alias("COMPUTER")] $COMPUTERNAME)
$env:COMPUTERNAME

 #$env:COMPUTERNAME

$REGISTRY = [MICROSOFT.WIN32.REGISTRYKEY]::OPENREMOTEBASEKEY('LOCALMACHINE',$COMPUTERNAME)
$REGISTRYKEY = $REGISTRY.OPENSUBKEY("SOFTWARE\\MICROSOFT\\INTERNET EXPLORER")
$VALUE = $REGISTRYKEY.GETVALUE("VERSION")

$VALUE
